db:
  image: postgres:9.6
  environment:
    - POSTGRES_USER=expenses
    - POSTGRES_PASSWORD=onetwothree
  volumes:
    - ./:/web
node:
  image: node:4.5.0
  volumes:
    - ./:/web
  links:
    - django:django
  expose:
    - "3000"
  ports:
    - "3000:3000"
  command: /bin/bash -c "cd /web/client/ && npm install && npm run build && npm run start"
django:
  image: adolgarev/python2:1473852567
  volumes:
    - ./:/web
  links:
    - db:db
  expose:
    - "9000"
  ports:
    - "9000:9000"
  environment:
    - DJANGO_SETTINGS_MODULE=expenses-app.settings
  command: /bin/bash -c "cd /web && pip install -r requirements.txt && exec invoke run_dev"